"""empty message

Revision ID: 33e058ca9cd1
Revises: 65528cdd4bf7
Create Date: 2017-01-24 15:41:06.143525

"""

# revision identifiers, used by Alembic.
revision = '33e058ca9cd1'
down_revision = '65528cdd4bf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
