"""empty message

Revision ID: 3a4227a54cfa
Revises: None
Create Date: 2016-11-17 16:26:12.826125

"""

# revision identifiers, used by Alembic.
revision = '3a4227a54cfa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('uri', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_list_description'), 'todo_list', ['description'], unique=True)
    op.create_index(op.f('ix_todo_list_status'), 'todo_list', ['status'], unique=True)
    op.create_index(op.f('ix_todo_list_title'), 'todo_list', ['title'], unique=True)
    op.create_index(op.f('ix_todo_list_uri'), 'todo_list', ['uri'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_list_uri'), table_name='todo_list')
    op.drop_index(op.f('ix_todo_list_title'), table_name='todo_list')
    op.drop_index(op.f('ix_todo_list_status'), table_name='todo_list')
    op.drop_index(op.f('ix_todo_list_description'), table_name='todo_list')
    op.drop_table('todo_list')
    ### end Alembic commands ###
